/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DjuVYq3fFFQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"

export function Username() {
  return (
    <div className="flex items-center space-x-2 rounded-lg border border-input bg-background px-3 py-2 shadow-sm">
      <span className="text-muted-foreground text-sm">Display.lol/</span>
      <Input
        type="text"
        placeholder="Enter your desired name"
        className="flex-1 border-none bg-transparent focus:ring-0 text-sm placeholder:text-muted-foreground"
      />
    </div>
  )
}
